// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	Type              pgtype.Text
	Provider          string
	ProviderAccountID string
	AccessToken       pgtype.Text
	RefreshToken      pgtype.Text
	ExpiresAt         pgtype.Timestamp
	TokenType         pgtype.Text
	Scope             pgtype.Text
	IDToken           pgtype.Text
	SessionState      pgtype.Text
	CreatedAt         pgtype.Timestamp
	UpdatedAt         pgtype.Timestamp
}

type Session struct {
	ID           pgtype.UUID
	SessionToken string
	RefreshToken string
	ExpiresAt    pgtype.Timestamp
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	UserID       pgtype.UUID
}

type User struct {
	ID            pgtype.UUID
	Name          string
	Email         string
	Image         pgtype.Text
	Username      string
	EmailVerified pgtype.Timestamp
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

type VerificationToken struct {
	Identifier string
	Token      string
	ExpiresAt  pgtype.Timestamp
}
